[package]
name = "multipr"
version = "0.0.1"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
googletest = "0.13"
tempfile = "3"

[[bin]]
name = "splitpr"
path = "src/splitpr.rs"
